openapi: 3.0.0
info:
  title: 'API Subsecretaría de Trabajo'
  description: 'Documentación de los servicios públicos de la Subsecretaría de Trabajo - Registro de Calderistas'
  version: 1.0.0
servers:
  -
    url: 'https://sstexroad.mendoza.gov.ar:8443/r1/mendoza/GPE/035/REGICERT'
    description: 'Ambiente de testing'
  -
    url: 'https://sstexroad.mendoza.gov.ar:8443/r1/mendoza/GPE/035/REGICERT'
    description: 'Ambiente de producción'
paths:
  /RegcalderistasTst:
    post:
      tags:
        - Calderistas
      summary: 'Valida si el profesional está registrado como calderista y devuelve los datos para generar la credencial.'
      operationId: adf79f62f9e0be2ea50f5eff5a206959
      parameters:
        -
          name: X-Road-Client
          in: header
          description: 'Identificador del subsistema consumidor autorizado en X-Road'
          required: true
          schema:
            type: string
            example: mendoza/GPE/035/REGICERT
        -
          name: X-Road-UserId
          in: header
          description: 'Usuario que inició la solicitud'
          required: false
          schema:
            type: string
            example: juan.perez
        -
          name: X-Road-Issue
          in: header
          description: 'Identificador único de la transacción (UUID v4 con prefijo de la app)'
          required: true
          schema:
            type: string
            example: RegcalderistasTst-1b4e28ba-2fa1-11d2-883f-0016d3cca427
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required:
                - dni
              properties:
                dni:
                  type: string
                  example: '30123456'
              type: object
      responses:
        200:
          description: 'Respuesta exitosa si el profesional está habilitado'
          content:
            application/json:
              schema:
                properties:
                  response:
                    properties:
                      flag:
                        type: string
                        example: SI
                      respuesta:
                        type: array
                        items:
                          properties:
                            nombre:
                              type: string
                              example: JUAN
                            apellido:
                              type: string
                              example: PEREZ
                            dni:
                              type: string
                              example: '30123456'
                            registro:
                              type: string
                              example: 1234/25
                            fecha_resolucion:
                              type: string
                              example: 06/10/2025
                            'expediente N°':
                              type: string
                              example: EX-12345-2025
                            fecha_emision:
                              type: string
                              example: 06/09/2025
                            letra:
                              type: string
                              example: C
                          type: object
                      error:
                        description: 'Lista de errores, puede estar vacía si no hubo errores'
                        type: array
                        items:
                          type: string
                        example: []
                    type: object
                type: object
        403:
          description: 'Credencial con fecha de baja'
          content:
            application/json:
              schema:
                properties:
                  response:
                    properties:
                      flag:
                        type: string
                        example: 'NO'
                      respuesta:
                        description: 'Siempre presente. Arreglo vacío en caso de error'
                        type: array
                        items:
                          type: string
                        example: []
                      error:
                        properties:
                          code:
                            type: integer
                            example: 403
                          message:
                            type: string
                            example: 'La credencial no se encuentra habilitada para su emisión.'
                        type: object
                    type: object
                type: object
        422:
          description: 'Datos inválidos o campos faltantes'
          content:
            application/json:
              schema:
                properties:
                  response:
                    properties:
                      flag:
                        type: string
                        example: 'NO'
                      respuesta:
                        description: 'Siempre presente. Arreglo vacío en caso de error'
                        type: array
                        items:
                          type: string
                        example: []
                      error:
                        properties:
                          code:
                            type: integer
                            example: 422
                          message:
                            type: string
                            example: "El campo 'tipo_carnet' contiene un valor inválido."
                        type: object
                    type: object
                type: object
        500:
          description: 'Error interno del servidor'
          content:
            application/json:
              schema:
                properties:
                  response:
                    properties:
                      flag:
                        type: string
                        example: 'NO'
                      respuesta:
                        description: 'Siempre presente. Arreglo vacío en caso de error'
                        type: array
                        items:
                          type: string
                        example: []
                      error:
                        properties:
                          code:
                            type: integer
                            example: 500
                          message:
                            type: string
                            example: 'Error interno del servidor'
                        type: object
                    type: object
                type: object
tags:
  -
    name: Calderistas
    description: Calderistas
